# login
POST http://localhost:8080/login

###

# query by id
GET http://localhost:8080/grocery/1
Authorization: Bearer ACCESS_TOKEN

###

# query all
GET http://localhost:8080/grocery
Authorization: Bearer ACCESS_TOKEN

###

# create new product
POST http://localhost:8080/grocery
content-type: application/json
Authorization: Bearer ACCESS_TOKEN

{
    "name" : "Test",
    "code" : "A001",
    "price" : 100
}

###

# delete by id
DELETE http://localhost:8080/grocery/2
Authorization: Bearer ACCESS_TOKEN